source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraCommonWrapperSwift_Example', :exclusive => true do
  pod "HaidoraCommonWrapperSwift", :path => "../"
end

target 'HaidoraCommonWrapperSwift_Tests', :exclusive => true do
  pod "HaidoraCommonWrapperSwift", :path => "../"

#  pod 'Quick'
#  pod 'Nimble'
end
